services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker
    volumes:
      - .:/app

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "5431:5432"

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6378:6379"
